version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aplication
    volumes:
      - ../..:/workspaces:cached
      - ~/.config:/home/node/.config
    env_file:
    - .env
    ports:
      - '${APP_PORT:-80}:80'
    command: sleep infinity  