version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    container_name: aplication
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity